x-runtipi:
  schema_version: 2

services:
  nominatim-api:
    container_name: nominatim-api
    image: mediagis/nominatim:5.2
    x-runtipi:
      is_main: true
      internal_port: 8080
    secrets:
      - nominatim_key
    restart: unless-stopped
    ports:
      - ${APP_PORT}:8080
    environment:
      PBF_URL: ${PBF_URL}
      # PBF_PATH: ${PBF_PATH}
      REPLICATION_URL: ${REPLICATION_URL}
      NOMINATIM_PASSWORD_FILE: /run/secrets/nominatim_key
      UPDATE_MODE: ${UPDATE_MODE}
      IMPORT_STYLE: ${IMPORT_STYLE}
      IMPORT_TIGER_ADDRESSES: ${IMPORT_TIGER_ADDRESSES}
      WARMUP_ON_STARTUP: true
    user: "${USER_UID}:${USER_GID}"
    volumes:
      - nominatim-db:/var/lib/postgresql/16/main
    shm_size: 128mb
    networks:
      - nominatim

volumes:
  nominatim-db:

secrets:
  nominatim_key:
    file: ./keys/nominatim_key.txt

networks:
  nominatim:
