x-runtipi:
  schema_version: 2

services:
  cyberchef:
    image: ghcr.io/gchq/cyberchef:v11.0.0
    container_name: cyberchef
    x-runtipi:
      is_main: true
      internal_port: 8080
    restart: unless-stopped
    ports:
      - ${APP_PORT}:8080
