services:
  keepassxc:
    image: lscr.io/linuxserver/keepassxc:latest
    container_name: keepassxc
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${APP_DATA_DIR}/config:/config
    ports:
      - ${APP_PORT}:3000
      - 3001:3001
    restart: unless-stopped
    networks:
      - tipi_main_network
