services:
  server:
    container_name: nominatim
    image: mediagis/nominatim:5.1
    secrets:
      - nominatim_key
    restart: unless-stopped
    ports:
      - 11111:8080
    environment:
      PBF_URL: ${PBF_URL}
      REPLICATION_URL: ${REPLICATION_URL}
      NOMINATIM_PASSWORD_FILE: /run/secrets/nominatim_key
      UPDATE_MODE: catch-up
      IMPORT_STYLE: full
      USER_UID: 1000
      USER_GID: 1000
    volumes:
      - ${APP_DATA_DIR}/data/nominatim-db/:/var/lib/postgresql/16/main
    shm_size: 1gb
    networks:
      - nominatim
  ui:
    container_name: nominatim-ui
    image: ghcr.io/camille-s/nominatim-ui:0.1.0
    depends_on:
      - nominatim
    restart: unless-stopped
    ports:
      - ${APP_PORT}:80
    networks:
      - nominatim

secrets:
  nominatim_key:
    file: ./keys/nominatim_key.txt

networks:
  nominatim:
