services:
  server:
    image: padloc/server
    build:
      context: github.com/padloc/padloc.git#main
      dockerfile: Dockerfile-server
    environment:
      PL_DATA_BACKEND: leveldb
      PL_DATA_LEVELDB_DIR: /data
      PL_DATA_ATTACHMENTS_BACKEND: fs
      PL_DATA_ATTACHMENTS_DIR: /attachments
      PL_SERVER_CLIENT_URL: http://localhost:${APP_PORT}
      PL_EMAIL_BACKEND: console
    ports:
      - 3000:3000
    volumes:
      - ${APP_DATA_DIR}/attachments:/attachments
      - ${APP_DATA_DIR}/data:/data
    restart: unless-stopped
    networks:
      - tipi_main_network
  pwa:
    image: padloc/pwa
    build:
      context: github.com/padloc/padloc.git#main
      dockerfile: Dockerfile-pwa
    environment:
      PL_SERVER_URL: http://localhost:3000
      PL_PWA_URL: http://localhost:${APP_PORT}
    ports:
      - ${APP_PORT}:8080
    restart: unless-stopped
    networks:
      - tipi_main_network
