x-runtipi:
  schema_version: 2

services:
  gitea:
    image: docker.gitea.com/gitea:1.26.0
    container_name: gitea
    x-runtipi:
      is_main: true
      internal_port: 3000
    restart: unless-stopped
    ports:
      - ${APP_PORT}:3000
    environment:
      USER_UID: ${USER_UID}
      USER_GID: ${USER_GID}
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
